# Generated by Django 4.1.5 on 2023-01-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_url", models.URLField()),
                ("parsed_url", models.URLField(default="Null")),
                ("image_path", models.CharField(default="Null", max_length=1000)),
                ("log", models.CharField(default="Null", max_length=1000)),
            ],
        ),
    ]
